FROM node:20-alpine

WORKDIR /app

# 复制依赖文件
COPY package.json ./

# 安装依赖
RUN npm install --production

# 复制 GeoLite2 数据库
COPY GeoLite2-City.mmdb ./

# 复制服务代码
COPY log-server.js ./

EXPOSE 3000

CMD ["node", "log-server.js"]